server:
  port: 8201

# 数据库配置
spring:
  application:
    name: property-menu    # 一组服务端对外暴露的名称  eureka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #数据源
    driver-class-name: org.gjt.mm.mysql.Driver          #mysql驱动包
    url: jdbc:mysql://localhost:3306/property_mi          #数据库名称
    username: root
    password: 5615123

# mybatis配置
mybatis:
  type-aliases-package: com.property.entity   #配置实体类别名
  mapper-locations:
    - classpath:mapper/**/*.xml             #mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: menu8201
    prefer-ip-address: true